// Shared projects data used across portfolio

export const projects = [
  {
    id: 1,
    img: '/images/orb.png',
    category: 'AI & Super Apps',
    title: 'IQBrands – Multi-Agent Super App',
    desc: 'A cutting-edge super app powered by multiple AI agents working in harmony. Automates intelligent workflows, delivers smart insights, and transforms business operations.',
    link: 'https://agentiqbrands.com/',
    tags: ['React', 'SCSS', 'AI Integration', 'Figma'],
  },
  {
    id: 2,
    img: '/images/ecomerce.png',
    category: 'E-Commerce',
    title: 'The 11-11 – Fashion & Lifestyle Store',
    desc: 'A full-featured e-commerce platform offering clothing, electronics, shoes and more. Delivers a seamless shopping experience with curated collections.',
    link: 'https://the11-11.com/',
    tags: ['E-Commerce', 'HTML5', 'Bootstrap', 'UI Design'],
  },
  {
    id: 3,
    img: '/images/car-auction.png',
    category: 'Automotive & Auctions',
    title: 'Taar – Car Auction Marketplace',
    desc: 'A dynamic online car auction marketplace where users can browse, bid and win vehicles. Real-time bidding, transparent listings, and trusted seller management.',
    link: 'https://taarauction.com/',
    tags: ['Car Bidding', 'Web Design', 'React UI', 'SCSS'],
  },
  {
    id: 4,
    img: '/images/nexphy.png',
    category: 'Health & Multivitamins',
    title: 'Nexphy – Health & Wellness Capsules',
    desc: 'A premium health and wellness platform for daily multivitamin capsules, nutritional supplements, and vitality products to boost overall health.',
    link: 'https://nexphy.in/',
    tags: ['Health & Wellness', 'E-Commerce', 'React UI', 'CSS3'],
  },
  {
    id: 5,
    img: '/images/taxsimba.png',
    category: 'Finance & Tax',
    title: 'TaxSimba – Self Tax Filing Platform',
    desc: 'An intuitive online tax management platform allowing users to hassle-free file, calculate and manage their taxes self-service online.',
    link: 'https://taxsimba.co.uk/',
    tags: ['Finance', 'Tax Calculator', 'Web UI', 'Bootstrap'],
  },
  {
    id: 6,
    img: '/images/cloths.png',
    category: 'Fashion & Lifestyle',
    title: 'Nomad – Ladies Fashion Apparel',
    desc: 'An elegant e-commerce platform for ladies fashion & clothing. Browse the latest trends in dresses, outfits and accessories with seamless navigation.',
    link: 'https://nomad.codebynish.com/',
    tags: ['Fashion', 'E-Commerce', 'Responsive UI', 'Figma'],
  },
  {
    id: 7,
    img: '/images/juice.png',
    category: 'Food & Beverage',
    title: 'Juice Bar & Refreshments',
    desc: 'A vibrant and fresh website for a juice café. Features a colorful menu, online ordering experience and a healthy lifestyle brand identity.',
    link: 'https://juice.codebynish.com/',
    tags: ['Food & Drink', 'UI Design', 'SCSS', 'Landing Page'],
  },
  {
    id: 8,
    img: '/images/weeding.png',
    category: 'Events & Rentals',
    title: 'Widoora – Wedding & Event Rentals',
    desc: 'A professional platform for renting wedding and event supplies. Offers furniture, décor and essentials for weddings, parties and outdoor functions.',
    link: 'https://www.widoora.com/',
    tags: ['Event Rentals', 'Web Design', 'Bootstrap', 'HTML5'],
  },
]
